data = """\
loretozaragozaa@mejillonesb.com|@LIfTMWERfL3|loreto2261@telefonica.net
omarmarcoi@mejillonesb.com|LDrvnhB8STLJ|omar8502@icloud.com
abrahamsanjuanc@mejillonesb.com|dD@e8XoGUaHA|abraham7866@telefonica.net
maricelabeltrank@mejillonesb.com|hsSnrqJ4C0eE|maricela3144@yahoo.com
aureliocaballeroi@mejillonesb.com|MRTnIDtISJdI|aurelio3428@hotmail.com
robertaescamillar@mejillonesb.com|h9kKPdIIekbF|roberta5224@terra.es
armidalastraa@mejillonesb.com|14cp@BmQvlsl|armida3718@live.com
marisaprati@mejillonesb.com|jkaxXWlw5n1o|marisa874@icloud.com
lunahernandoc@mejillonesb.com|FrTupePQJRuo|luna212@gmail.com
javieracarballoc@mejillonesb.com|60GXaMixcTOW|javiera1949@live.com
felisapinat@mejillonesb.com|DJmW7MNIaCvN|felisa3987@telefonica.net
josefazamoranot@mejillonesb.com|LLV7os2@rGKh|josefa8762@ono.com
carmengimenoe@mejillonesb.com|tSpwJT943@OZ|carmen2150@gmail.com
dimasarcosr@mejillonesb.com|WNoNPy13kLxm|dimas4399@orange.es
aureliamayorald@mejillonesb.com|62ZQIIFlh5Cz|aurelia1401@zoho.com
benitaurrutiad@mejillonesb.com|1WmpgPKYDzH7|benita4029@orange.es
carmelitabarrancop@mejillonesb.com|nPj4QLySZrZN|carmelita3297@orange.es
rosalinaaramburug@mejillonesb.com|n4pcI8oJcuR8|rosalina3019@telefonica.net
gemaponces@mejillonesb.com|Z1h4JrQJQGtj|gema4688@gmail.com
prudenciabotellas@mejillonesb.com|ANjr0w6D3I6B|prudencia4146@vodafone.es
amayacomasp@mejillonesb.com|OuDpvgDNA3EZ|amaya3157@icloud.com
anareyeso@mejillonesb.com|nHg0u4VgYivz|ana7931@outlook.com
conradoluzd@mejillonesb.com|lO1qgAlZtMJD|conrado3211@terra.es
vanesaposadah@mejillonesb.com|XYjJShH9CEen|vanesa4410@vodafone.es
pascualaborrellc@mejillonesb.com|SMOsgN085BnI|pascuala7829@hotmail.com
fidelasobrinop@mejillonesb.com|fHuxECrbdW7o|fidela6300@terra.es
delfinasalesh@mejillonesb.com|2TZMNhkUIe@3|delfina3878@telefonica.net
pastorreya@mejillonesb.com|nAJ@3T0HyKIb|pastor8893@outlook.com
valeroaranal@mejillonesb.com|499ZNooOWCeN|valero4848@yahoo.com
domingacazorlaa@catolicomercedesb.org|egG08bcDtoQ@|dominga805@gmail.com
maximilianoarnalm@catolicomercedesb.org|83IkAlyD4gLl|maximiliano3454@live.com
leticiagrasr@catolicomercedesb.org|6zQlTYyO@djN|leticia3316@outlook.com
ulisesalcarazb@catolicomercedesb.org|kMi4Rk$6Yn9$|ulises5799@ono.com
narcisomoyas@catolicomercedesb.org|JtqPSTGrFGnj|narciso6834@terra.es
florentinovergarac@catolicomercedesb.org|ihUJdO5rqkAp|florentino278@telefonica.net
nicodemogimenoa@catolicomercedesb.org|SvSuUGHs2M8w|nicodemo3494@hotmail.com
tamaraquirogag@catolicomercedesb.org|jLsfnL06lg21|tamara385@telefonica.net
teobaldougartee@catolicomercedesb.org|Mw0aCEeyrZU$|teobaldo3365@icloud.com
ciprianobalagueri@catolicomercedesb.org|5QlTmuBTX8tP|cipriano4000@vodafone.es
joanmateosd@catolicomercedesb.org|wOmiCY6rJ83o|joan8094@terra.es
paolapalacioi@catolicomercedesb.org|0gbD3sHvQXOr|paola896@live.com
dulcearanaa@catolicomercedesb.org|FvRT3cB$QbDc|dulce8082@gmail.com
florindafuentesg@catolicomercedesb.org|Vrf4olWx5eId|florinda7311@icloud.com
zaidacriador@catolicomercedesb.org|8kSIZdCkAU3c|zaida5212@hotmail.com
yagopomaresl@catolicomercedesb.org|QX9T9mpZI7h5|yago5713@yahoo.com
quiquemorenoh@catolicomercedesb.org|dHu5VEq8ry3V|quique1257@ono.com
benignacontrerass@catolicomercedesb.org|L491s760f8eL|benigna4039@live.com
zaidaanguitat@catolicomercedesb.org|zY$cB@6fQeVD|zaida4068@hotmail.com
elianaestebanl@catolicomercedesb.org|ICt1e151je9$|eliana4578@yahoo.com
"""